apiVersion: v1
kind: Pod
metadata:
  name: alpine-python-pod
spec:
  containers:
  - name: alpine-python-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "apk add --no-cache python3 && python3 -c 'print(\"Hello, Python!\")'; sleep infinity"]
